import db from '../../db/connector.js';
import { NotabugDB } from './NotabugDB.js';
import { NotabugHelpers } from './NotabugHelpers.js';

export class SystemController {
  static async tick(req, res) {
    try {
      const bugs = await db.query(
        "SELECT * FROM notabug_bugs WHERE status IN ('open','claimed') ORDER BY RANDOM() LIMIT 3"
      );

      for (const bug of bugs.rows) {
        await SystemController.#processBugTick(bug);
      }

      const openBugsCount = await NotabugDB.getOpenBugsCount();

      if (Math.random() > 0.6 && openBugsCount < NotabugHelpers.MAX_OPEN_BUGS) {
        await SystemController.#spawnRandomBug();
      }

      res.json({ ok: true });
    } catch (err) {
      res.status(500).json({ ok: false });
    }
  }

  static async #processBugTick(bug) {
    const roll = Math.random();

    if (roll < 0.15) {
      const newChaos = Math.min(100, bug.chaos_level + Math.floor(Math.random() * 15) + 5);
      await db.query(
        'UPDATE notabug_bugs SET chaos_level = $1, severity = CASE WHEN $1 > 80 THEN $2 ELSE severity END WHERE id = $3',
        [newChaos, 'critical', bug.id]
      );
      await NotabugDB.addMutation(bug.id, 'Severity escalated automatically');
      await NotabugDB.addFeedEvent(`<span class="chaos-ref">⚠ Bug #${bug.id} mutated — chaos rising</span>`);
    }

    if (roll > 0.95) {
      await db.query("UPDATE notabug_bugs SET status = 'escaped' WHERE id = $1", [bug.id]);
      await NotabugDB.addMutation(bug.id, 'Bug escaped containment');
      await NotabugDB.addFeedEvent(`<span class="chaos-ref">🚨 Bug #${bug.id} has escaped!</span>`);
    }
  }

  static async #spawnRandomBug() {
    const title = NotabugHelpers.RANDOM_BUG_TITLES[
      Math.floor(Math.random() * NotabugHelpers.RANDOM_BUG_TITLES.length)
    ];
    const severity = NotabugHelpers.RANDOM_SEVERITIES[
      Math.floor(Math.random() * NotabugHelpers.RANDOM_SEVERITIES.length)
    ];
    const chaos = Math.floor(Math.random() * 70) + 10;

    const newBug = await db.query(
      'INSERT INTO notabug_bugs (title, description, severity, chaos_level, status) VALUES ($1, $2, $3, $4, $5) RETURNING id',
      [title, 'Auto-generated by system entropy engine.', severity, chaos, 'open']
    );

    await NotabugDB.addMutation(newBug.rows[0].id, 'Spawned by entropy engine');
    await NotabugDB.addFeedEvent(`System spawned <span class="bug-ref">#${newBug.rows[0].id}</span>: <span class="highlight">${title}</span>`);
  }
}
